const BARCODE_SCANNER_BEFORE_START_EVENT = 'barcode-scanner:beforestart'
const BARCODE_SCANNER_DECODE_FRAME_EVENT = 'barcode-scanner:decode-frame'
const BARCODE_SCANNER_START_EVENT = 'barcode-scanner:start'
const WORKER_DECODE_FAILURE_CAUSE = 'decode-failure'
const WORKER_DECODE_TIMEOUT = 1000 * 16
const WORKER_DECODE_TIMEOUT_CAUSE = 'decode-timeout'
const WORKER_LOAD_FAILURE_CAUSE = 'worker-load-failure'
const WORKER_LOAD_TIMEOUT = 1000 * 32
const WORKER_LOAD_TIMEOUT_CAUSE = 'worker-load-timeout'

export {
    BARCODE_SCANNER_BEFORE_START_EVENT,
    BARCODE_SCANNER_DECODE_FRAME_EVENT,
    BARCODE_SCANNER_START_EVENT,
    WORKER_DECODE_FAILURE_CAUSE,
    WORKER_DECODE_TIMEOUT,
    WORKER_DECODE_TIMEOUT_CAUSE,
    WORKER_LOAD_FAILURE_CAUSE,
    WORKER_LOAD_TIMEOUT,
    WORKER_LOAD_TIMEOUT_CAUSE,
}
